import File from '../models/File';

class FileController {
  async store(req, res) {
    // req.file is generated by multer as a middleware
    const { originalname: name, filename: path } = req.file;

    const file = File.create({
      name,
      path,
    });

    return res.json(file);
  }

  async index(req, res) {
    const { id } = req.params;
    const signature = File.findByPk(id);

    return res.json(signature);
  }
}

export default new FileController();
